Repository cal-itp/data-analyses, pull requests merged in 2022-05, with the labels that each got.

#207 Highway corridors
  bus_service_increase/C7_map_competitive_routes.ipynb
  bus_service_increase/C7_target_highway_corridors.ipynb
  bus_service_increase/setup_corridors_stats.py
Labels: analytics research

#211 issue template: added research request issue template
  .github/ISSUE_TEMPLATE/research-request.md
Labels: enhancement

#219 workflows: revised the board automations workflow to include the newl…
  .github/workflows/board-move-issues.yml
Labels: enhancement

#237 github: created new documentation issue template and workflow
  .github/ISSUE_TEMPLATE/docs.md
  .github/workflows/board-move-issues.yml
Labels: admin

#239 Portfolio yaml examples
  Makefile
  portfolio/highway_corridors.yml
  portfolio/rt_parallel.yml
Labels: documentation, portfolio request
