Repository cal-itp/data-analyses, pull requests merged in 2024-02, with the labels that each got.

#1014 expand hqta readme based on HCD feedback
  high_quality_transit_areas/README.md
Labels: open-data

#1018 Clean up shared utils
  _shared_utils/precommit.txt
  _shared_utils/requirements.txt
  _shared_utils/setup.py
  _shared_utils/shared_utils/__init__.py
  _shared_utils/shared_utils/calitp_color_palette.py
  _shared_utils/shared_utils/geog_utils_to_add.py
  _shared_utils/shared_utils/geography_utils.py
  _shared_utils/shared_utils/gtfs_utils.py
  _shared_utils/shared_utils/styleguide.py
  _shared_utils/shared_utils/utils.py
  _shared_utils/shared_utils/utils_to_add.py
  portfolio/requirements.txt
  rt_segment_speeds/requirements.txt
Labels: tooling

#1019 Fix shared utils imports
  _shared_utils/requirements.txt
  _shared_utils/shared_utils/dask_utils.py
  _shared_utils/shared_utils/gtfs_utils_v2.py
  _shared_utils/shared_utils/rt_dates.py
  _shared_utils/shared_utils/rt_utils.py
Labels: tooling

#1026 Refresh TIMS data
  safety_projects/update_tims_2021.py
Labels: data
